{% set name = "git-bash" %}
{% set version = "2.23.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://anaconda.org/anaconda/7za/920/download/win-64/7za-920-0.tar.bz2
    sha256: 356190e3e3569cb55114ee19da2a9bb793f26329df22ba79441749f89e9ca60a
  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-64-bit.7z.exe
    sha256: 501d8be861ebb8694df3f47f1f673996b1d1672e12559d4a07fae7a2eca3afc7

build:
  skip: True  # [not win64]
  number: 0
  no_link:
    - Library/{{ name }}/*
    - bin/*

requirements:
  build:
    - m2-patch

test:
  commands:
    - |
      cmd /c %PREFIX%\bin\bash.bat --version
    - |
      cmd /c %PREFIX%\bin\bash.bat -c "if [[ $(echo hello | cp /dev/stdin /dev/stdout) != 'hello' ]]; then exit 1; fi"

about:
  home: https://git-scm.com/
  license: "git: GPLv2, LGPLv2.1, bash: GPLv3+"
  license_file: LICENSE.txt
  summary: "Repackage of the Git Bash for Windows."

extra:
  recipe-maintainers:
    - kiwi0fruit
