{% set name = "git-bash" %}
{% set version = "2.21.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-64-bit.7z.exe   # [win64]
  sha256: 208926e53fa4bd11a1379fddcaf26e49ff08dc4c589dd2570a1307c31b3b9939  # [win64]

build:
  skip: True  # [not win64]
  number: 0
  no_link:
    - Library/{{ name }}/*
    - bin/*

requirements:
  build:
    - 7za
    - m2-patch

test:
  commands:
    - |
      cmd /c %PREFIX%\bin\bash.bat --version
    - |
      cmd /c %PREFIX%\bin\bash.bat -c "if [[ $(echo hello | cp /dev/stdin /dev/stdout) != 'hello' ]]; then exit 1; fi"

about:
  home: https://git-scm.com/
  license: "git: GPLv2, LGPLv2.1, bash: GPLv3+"
  license_file: LICENSE.txt
  summary: "Repackage of the Git Bash for Windows."

extra:
  recipe-maintainers:
    - kiwi0fruit
