travis:
  secure:
    BINSTAR_TOKEN: bB3WA0OdgivJYC/ZeT0KiWpMiJQFJrIx7LmsjOnNJaipgmHWhbpNPQIbusRK//frbFAR8H/VNG3EHB5u/x0xxVUl9lqob0dzkQuqfkJVFCu/7RzpqJGD+aebRc4Fet0kWomPI6b6957CuI9jhwDpE6SVZKox1DYHCMxdUvWR+mOlgh9EX8mbeQ1ylazMJ9J8fTqB8rZFNPcaX/81gExRtjx61motLXBYOFYSoyicp3+hRdZwMSsb4UVhDGkwJPWAlkDBJr2gmJkoWkDBxjTh+YNxb11aAQP8Fx8C5v71sX18cEV/kMFbbwhjynNc1OdtS/2tfVsS0s0TjcdfLDhFJi3+o0kvzUJyT+nZ7tAQqT6tN/Z+8xwdCFVor0HCJ5xAqyjyz15Dpejx6AvfqOddPzERx0gcQLW5PrWIBRgmcaxJ507tJbkI6xeKYfe8/VyXM192mHfwjz4ggyVnAM9dpROVGHth7JOttSQyf0kxaf9uZijHvJAFkR7F/2JhFvaNAn0TxMRKUA6Y8bUtC2et+sg576SkA3I2V0VNwLpFSrV/4ioY5YqPGxmeZjoASvXPR4XWIRDFWLjHVeYrIQzES8QdrUL47U0UcroGKWGEfX0gQO8V6aR2BbleQim7nVDU/UUR4Nt5NzQRcsWAW3Ee9tXohn9+gcwv4zqmPvRY9zM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
